name: "Feature Request"
description: "Suggest an idea for this project using this fun template!"
labels: ["feature request", "flag: needs core member"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! Before you submit, please make sure to ensure the following is kept up with:

        - that the feature request is not already in the [issue tracker](https://github.com/irisu01/sulfurous/issues)
        - that it isn't just a quick addition or question that can be answered in the [Discord server]()
        
        ---

  - type: checkboxes
    attributes:
      label: Is this feature request already in the issue tracker?
      description: Please make sure to check if the feature request is already in the [issue tracker](https://github.com/irisu01/sulfurous/issues).
      options:
      - label: "I have checked the issue tracker and this feature request is not already in the issue tracker."
        required: true

  - type: textarea
    attributes:
      label: Describe the feature request
      description: Please describe the feature request in as much detail as possible.
      placeholder: I would like to see..., I think it would be cool if..., I think it would be better if..., I have an issue with...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: Please describe the solution you'd like in as much detail as possible.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you've considered, if any.
      description: Please describe any alternative solutions or features you've considered.
      placeholder: I have considered..., I have tried..., I have looked into...